### PR TITLE
Error message fixes: descriptive error, set to Payment error for now

### LINKED ISSUE #1680: Clarify Out of Capacity Error
It is hard to know when a transaction is rejected at the RPC level due to being out of capacity.

Should we use the `InvalidTransaction::Payment` error instead of `InvalidTransaction::Custom(self as u8)`?

Current Code:
```
impl ChargeFrqTransactionPaymentError {
  pub fn into(self) -> TransactionValidityError {
	TransactionValidityError::from(InvalidTransaction::Custom(self as u8))
  }
}
```

### PR DESCRIPTION
**Pull request by saraswatpuneet**
# Goal
The goal of this PR is to return descriptive error for some capacity related checks
* return `Payment` error in places of `BelowMinDeposit` and `TargetCapacityNotFound` to better catch errors at client side

Closes #1680 

# Discussion

# Checklist
- [x] Chain spec updated
- [ ] Custom RPC OR Runtime API added/changed? Updated js/api-augment.
- [ ] Design doc(s) updated
- [ ] Tests added
- [ ] Benchmarks added
- [ ] Weights updated

### CODE REVIEW

**Review by wilwade — CHANGES_REQUESTED** [review]
Looks good to me, but have some left over commented out code.

**Comment by saraswatpuneet** [comment]
@wilwade  i left them for reference (in case we wanted to know possible reasons) but removed them in latest commit

**Review by wilwade — APPROVED** [review]
Looks good to me.

**Review by mattheworris — APPROVED** [review]
I read through the code but did not run any tests.
Looks good from that perspective.

**Pull request merged**
