### PR TITLE
1911 bug granting a new delegation to a provider after revoking a delegation for that provider does not update the delegation correctly

### LINKED ISSUE #1911: [bug] Granting a new delegation to a provider after revoking a delegation for that provider does not update the delegation correctly
# Description
When granting a delegation to a provider who has previously had their delegation revoked (for the same MSA), the delegation storage is not updated correctly, resulting in no delegation.

# Steps to reproduce
1. MSA grants delegation to Provider 1 for some set of schemas
2. MSA revokes delegation for Provider 1. Delegation on chain now shows revokedAt with the block number for main delegation
3. MSA grants a new delegation to Provider 1 for some set of schemas

Delegation on chain still shows `revokedAt` with the same block number for the main delegation (`revokedAt` for various schemas is updated correctly).
Further attempts to call `revokeDelegationByDelegator` or `revokeDelegationByProvider` result in RPC error 1010 (Custom error 0) "Invalid Transaction" (this appears to be correct behavior; error code 0 seems to be InvalidDelegation returned from the signed extension CheckFreeExtrinsicUse)

# Acceptance Criteria
- [ ] `revokedAt` for a provider delegation should always be set to zero for an active delegation
- [ ] unit tests cover this scenario

### PR DESCRIPTION
**Pull request by JoeCap08055**
# Goal
The goal of this PR is to ensure that a delegation that was previously revoked, is properly made valid again after a new `grantDelegation` extrinsic is executed.

Closes #1911 

# Checklist
- [x] Chain spec updated
- [ ] Custom RPC OR Runtime API added/changed? Updated js/api-augment.
- [ ] Design doc(s) updated
- [x] Tests added
- [ ] Benchmarks added
- [ ] Weights updated

### CODE REVIEW

**Review by saraswatpuneet — APPROVED** [review]
Lgtm

Should we add a integration test ?

**Review by enddynayn — APPROVED** [review]
LGTM 👍

**Comment by JoeCap08055** [comment]
> Lgtm
> 
> Should we add a integration test ?

Sure, why not. I'll add one.

**Review by wilwade — APPROVED** [review]
Looks good to me. Thanks for the tests!

- ✅ Reviewed code and tests

**Review by mattheworris — COMMENTED** [review]
Suggest adding `cd e2e && npm run format` to the `Makefile` `format` target.
I have been bit by e2e test formating as well.

**Review by shannonwells — COMMENTED** [review]
I reviewed the code only. Looks good to me.  :shipit:

**Pull request merged**
