### PR TITLE
Reverse the Delegator/Provider storage map order

### PR DESCRIPTION
**Pull request by johnmela**
# Goal
The goal of this PR is to reverse the ordering of keys (provider, delegator) -> (delegator, provider)
in the `ProviderInfoOf` double storage map to make removal of delegations more efficient

References #310

### CODE REVIEW

**Review by enddynayn — APPROVED** [review]
fabulous!

**Comment by saraswatpuneet** [comment]
@johnmela  do you have to run benchmarks again and update the weights? give the storage is changed

**Review by saraswatpuneet — APPROVED** [review]
Let one comment

**Comment by johnmela** [comment]
@saraswatpuneet I have rerun benchmarks against the MSA pallet and updated the weights

**Review by saraswatpuneet — APPROVED** [review]

**Pull request merged**
