### PR TITLE
Jenkinsfile test

### PR DESCRIPTION
**Pull request by Bipin143**
# Goal
The goal of this PR is 

Closes 

# Discussion

# Checklist
- [ ] Chain spec updated
- [ ] Updated the js/api-augment code if a custom RPC added/changed
- [ ] Design doc(s) updated
- [ ] Tests added
- [ ] Benchmarks added
- [ ] Weights updated

### CODE REVIEW

**Comment by Bipin143** [comment]
opened PR to test, It can be deleted

**Review by jacobmfoley — APPROVED** [review]

**Pull request closed without merging**
