### PR TITLE
Exploring the issues behind error compiling the polkadot-cli using Ubuntu 

### PR DESCRIPTION
**Pull request by allanperlee**
# Goal
This is to explore the compilation issues when building the polkadot-cli; this doesn't close an issue

# Discussion
What is missing in the Ubuntu development environment that cannot build the polkadot-cli?

# Checklist
- [ ] Chain spec updated
- [ ] Custom RPC OR Runtime API added/changed? Updated js/api-augment.
- [ ] Design doc(s) updated
- [ ] Tests added
- [ ] Benchmarks added
- [ ] Weights updated

### CODE REVIEW

**Comment by aramikm** [comment]
@allanperlee This seems to be building as expected on linux. What is the error you see on your side? Please provide the whole error. Thanks

**Comment by allanperlee** [comment]
Hi @aramikm, they're the same errors that were mentioned in the other issue. Since it is building expectedly, could I submit this for review? Thanks!
Screenshot 2023-11-07 175823
Screenshot 2023-11-07 175929

**Comment by aramikm** [comment]
@allanperlee were you able to figure out the issue?  The issue might be related to not having the `glibc` library. A quick search returns something lie the following https://www.reddit.com/r/rust/comments/16upmfq/help_with_rust_linking_with_cc_error_linking_with/

**Comment by allanperlee** [comment]
Hi @aramikm, it seems that I already have that library installed. Let me show you the command and result:
Screenshot 2023-11-28 211945

**Comment by aramikm** [comment]
Please go over these steps again and let me know if you still have issues https://docs.substrate.io/install/linux/

**Comment by allanperlee** [comment]
@aramikm I'm sorry, but I'm still got the same error after following the steps on the Substrate website provided. Below are active toolchains: 
Screenshot 2023-11-29 143809
Entire error:
[error linking with `cc` failed exit.txt](https://github.com/LibertyDSNP/frequency/files/13505748/error.linking.with.cc.failed.exit.txt)

**Comment by aramikm** [comment]
It might be you are running out of memory during linking process https://blog.inventic.eu/2012/07/linux-c-linker-ld-terminated-with-signal-9/

I think your rust version is also too high. we have moved to use stable version recently. This is my toolchain but it's on macos

active toolchain
----------------

1.70.0-aarch64-apple-darwin (overridden by '/Users/aa/source/mrc2/mrc/rust-toolchain.toml')
rustc 1.70.0 (90c541806 2023-05-31)

**Comment by allanperlee** [comment]
@aramikm I followed the steps for the linking memory failure and it built everything but the frequency-bin. Could my machine be the problem?  
[error linking with `cc` failed exit.txt](https://github.com/LibertyDSNP/frequency/files/13508635/error.linking.with.cc.failed.exit.txt)

**Comment by aramikm** [comment]
I think most probably your machine does not have enough memory. You can check the memory consumption during compilation to check that.

**Comment by allanperlee** [comment]
It seems so, my compilation times are about 6 hours, is that normal? That was a brilliant discovery by the way, I was amazed. If I need another machine to compile this and thus pull request, I am willing to continue making contributions if this results in a paid role within this project, even if temporary or limited.

**Comment by aramikm** [comment]
I think your local machine is underpowered for what is required to build our current codebase. It usually takes less than 10 minutes if compiled from scratch.
In future we will have community contribution rewards and bug bounty programs which might pay some Frequency tokens for contributions. In terms employment, unfortunately right now we don't have any open positions that I know about.

**Comment by allanperlee** [comment]
@aramikm figured. I'm unemployed, surviving, so I cannot purchase new equipment. I'm sorry I couldn't solve these issues.

**Comment by aramikm** [comment]
No worries. Best wishes on your job search journey!

**Comment by aramikm** [comment]
Closing this exploratory PR

**Pull request closed without merging**
